//
//  StyleKitName.h
//  ProjectName
//
//  Created by Andres Ruggiero on 3/25/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawCanvas1WithBaseCurrencyName: (NSString*)baseCurrencyName baseCurrency: (NSString*)baseCurrency exchangeRate: (NSString*)exchangeRate;

@end
